name: allergies
description: Common allergy codes and descriptions

values:
  - code: "PCN"
    description: "Penicillin"
    type: "DA"
  - code: "ASA"
    description: "Aspirin"
    type: "DA"
  - code: "SUL"
    description: "Sulfa Drugs"
    type: "DA"
  - code: "COD"
    description: "Codeine"
    type: "DA"
  - code: "LAT"
    description: "Latex"
    type: "EA"
  - code: "PNT"
    description: "Peanuts"
    type: "FA"
  - code: "SHL"
    description: "Shellfish"
    type: "FA"
  - code: "EGG"
    description: "Eggs"
    type: "FA"
  - code: "IOD"
    description: "Iodine"
    type: "DA"
  - code: "MOR"
    description: "Morphine"
    type: "DA"
