name: religions
description: HL7 religion codes

values:
  - code: "CHR"
    description: "Christian"
  - code: "JEW"
    description: "Jewish"
  - code: "MOS"
    description: "Muslim"
  - code: "HIN"
    description: "Hindu"
  - code: "BUD"
    description: "Buddhist"
  - code: "NON"
    description: "None"
  - code: "OTH"
    description: "Other"
